buildscript {
    repositories {
        google()
        mavenCentral() // ده البديل الصحيح لـ jcenter
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
