name: Build PRIME APK

on:
  push:
    branches: [ main ] # اتأكد إن اسم الفرع عندك master زي ما باين في الصورة

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PRIME-Mobile-Launcher
          path: app/build/outputs/apk/debug/app-debug.apk
